### ISSUE TITLE
auth_on_publish and auth_on_subscribe not be invoked

### ISSUE THREAD

**Issue by TangMonk** [erlio/vmq_diversity#14]
``` lua

function my_auth_on_register(reg)
    log.info('my_auth_on_register')
    return true
end

function my_auth_on_publish(pub)
    log.info('my_auth_on_publish')
    return false
end

function my_auth_on_subscribe(sub)
    log.info('my_auth_on_subscribe')
    return false
end

hooks = {
    auth_on_register = my_auth_on_register,
    auth_on_publish = my_auth_on_publish,
    auth_on_subscribe = my_auth_on_subscribe
}
```

I check the `console.log`, Only `my_auth_on_register` be invoked, `auth_on_publish` and `auth_on_subscribe` not invoke

**Comment by ioolkos** [comment]
Hello @TangMonk thanks!
So your `my_auth_on_publish` isn't called at all if you publish a message, for example? 
@dergraf is any step or config missing here?

**Comment by TangMonk** [comment]
@ioolkos thanks for your reply, I try to publish and subscribe, not works

**Comment by TangMonk** [comment]
I record my operation to a video for better explain: http://recordit.co/nvS3zYMWzq

**Comment by ioolkos** [comment]
Great way to explain!
Obviously both functions are not called as you are able to subscribe and publish.
Hm... let's see what @dergraf or @larshesel say (still asleep?... :)

**Comment by dergraf** [comment]
My guess is that there are other plugins which are returning 'ok' before `vmq_diversity` is called. Can you check with `vmq-admin plugin show` and check that e.g. the default `vmq_acl` is disabled or the default acl rule `#` is removed in `/etc/vernemq/vmq.acl`.

**Comment by larshesel** [comment]
Hi @TangMonk did you resolve the issue? Otherwise let us know - closing this for now.
