### ISSUE TITLE
Using haproxy, is there any way to pass client ip so it shows up in plugins?

### ISSUE THREAD

**Issue by vladbabii** [erlio/vmq_diversity#17]
Hello,
Is there any way set haproxy and vernemq in a way that:
- client connects to haproxy on different interface(s)
- haproxy sends connection to vernemq
- in vernemq using webhooks or diversity (or any other method) get the ip of client

Right now I'm using haproxy in TCP mode for mqtt tcp connections.

Thank you!

**Comment by dergraf** [comment]
Hi @vladbabii, what you're referencing to is the use of the HAProxy PROXY protocol, which enables to pass the client source IP Address/Port  to the upstream (balanced) server. The current release has no support for the PROXY protocol, but we're planing to add it in an upcoming release.

Please note that adding PROXY support for plain MQTT is quite straightforward, adding it for Websocket connections is another story, as the underlying Websocket Server (Cowboy) requires to support it. Therefore an initial version will likely only target MQTT and not MQTT-WS.

**Comment by vladbabii** [comment]
Thank you @dergraf, the HAProxy PROXY protocol for mqtt TCP connections is enough for me.

**Comment by dergraf** [comment]
see https://github.com/erlio/vmq_server/pull/102:)
