### ISSUE TITLE
mongodb.ensure_pool - No function clause matching mongo_protocol:binarize("test-db") line 105

### ISSUE THREAD

**Issue by tkaarrela** [erlio/vmq_diversity#2]
I try to create plugin that connects to mongodb but plugin crashes to ensure_pool call. 

```
CRASH REPORT Process <0.383.0> with 0 neighbours crashed with reason: no function clause matching mongo_protocol:binarize("test-db") line 105
```

**script content:**

```
function my_auth_on_register(reg)
    log.info("auth on register called")

    local config = {
        pool_id = "test-db-pool",
        login = "dbuser",
        password = "dbpassword",
        host = "192.168.99.100",
        size =1,
        port=37017,
        database = "test-db"
    }

    log.info("mongo pool_id: " .. config.pool_id)
    log.info("mongo login: " .. config.login)
    log.info("mongo password: " .. config.password)
    log.info("mongo host: " .. config.host)
    log.info("mongo port: " .. config.port)
    log.info("mongo db: " .. config.database)

    mongodb.ensure_pool(config)

    return true
end
```

From mongodb logs I can see that connection was created correctly.

**Comment by dergraf** [comment]
Ok. you probably spotted a bug with the given database config parameter. I guess it works if you can remove the database property.

I would also recommend you to keep the config and mongodb.ensure_pool(config) outside of the function definitions, so they are evaluated at script load time.

**Comment by tkaarrela** [comment]
Removed database (additionally removed authentication) from config and connection was created without errors.

Thanks for the tip about config and ensure_pool positioning

**Comment by tkaarrela** [comment]
Seems to be fixed to master and database configuration works now.
