### ISSUE TITLE
How to provide configuration parameters to plugin

### ISSUE THREAD

**Issue by tkaarrela** [erlio/vmq_diversity#4]
I was thinking about creating docker container that contains vernemq + vmq_diversity + own custom plugins written with vmq_diversity and started to wonder how can I provide configuration parameters dynamically to plugin.

I have plugin where I have mongo configuration which values I would not like to hardcode to plugin script.

Is there a way to read environment variable with vmq_diversity or do I need to use http module to fetch configuration parameters from discovery service? Is http module usable during initialization phase?

**Comment by baranga** [comment]
@tkaarrela I just solved this issue for me. My lua script looks like this:

``` lua
foo = os.getenv("FOO")
bar = os.getenv("BAR")
...
```

Now you just need to get the environment variables into vernemq. Thats a bit tricky as a plain `vernemq start` doesn't use your current environment. But you can use the daemon default config file for that: `/etc/default/vernemq`

``` bash
export FOO=foo
export BAR=bar
```

I just generate that file now every time the container starts via a start script.

**Comment by dergraf** [comment]
@tkaarrela did you manage to solve this issue, how did it go? I close this for the moment. Please feel free to reopen if the issue still remains.
