### ISSUE TITLE
auth_on_register username/password  are "undefined"

### ISSUE THREAD

**Issue by baranga** [erlio/vmq_diversity#5]
Username/password parameter in `auth_on_register` hook are strings with value "undefined" if connecting client doesn't send username/password.

How can I distinguish between client send nothing and client really send "undefined" as username/password? Maybe a empty username/password should be represented by `nil` or `false`.

**Comment by harmoniqpunk** [comment]
@baranga 

Hi Henning,

I also had same question and I decided to not handle unknown clients. I only handle recognizable clients. Otherwise I return false. Erlio encourages you to pass the handler to the next handler in the chain if you don't recognize the client:

> In case the plugin doesn't know the client it is best to return next as this would allow subsequent plugins in the chain to validate this client. If no plugin is able to validate the client it gets automatically rejected.

From [here](https://vernemq.com/docs/plugindevelopment/sessionlifecycle.html)

**Comment by baranga** [comment]
@georgepoenaru 
Hi George,
I want pass to next handler as fast as possible without expensive credential lookup if username is empty. Also if somehow "undefined"/"undefined" ends up in your backend then clients without credentials would pass the check.

**Comment by dergraf** [comment]
I guess the proper solution would pass an empty string as the username and nil if no username is set. Afaict this is how it works for Erlang plugins. Have to check the situation for diversity.

**Comment by harmoniqpunk** [comment]
@baranga Fair enough. I'm in control of all clients and I handled there. I guess is just a matter of how lua wrapper handle the Peer object in diversity.

**Comment by larshesel** [comment]
We just merged a fix for this. Instead of a string with value "undefined", `nil` is now passed.
