### ISSUE TITLE
Luerl - os.getenv("string") throw {error,function_clause}

### ISSUE THREAD

**Issue by harmoniqpunk** [erlio/vmq_diversity#7]
Hi, 

I need to use an env var ($API_STAGE) in a function hooked to auth_on_register. So I used:

```
stage = os.getenv("API_STAGE")
log.info(stage)
```

It look's like [luerl does support os.getenv](https://github.com/rvirding/luerl#currently-implemented-functions-in-the-libraries)

However calling log.info against stage string throws this error:

> {clean_session,true}] in "/auth/_build/default/lib/vmq_diversity/priv/../scripts/auth.lua" due to {error,function_clause}

I suppose that console.info doesn't support the string returned from os.getenv. Is this a string encoding issue ? Do you have any idea how to debug this ?

**Comment by larshesel** [comment]
Hi @georgepoenaru I think if the env var is not set `os.getenv/1` returns `nil` which will make `log.info/1` throw an exception. Could that be the case you're running into? In any case I think it would be a good idea to add the check for `nil` and do whatever needs to be done if the env var isn't set.

**Comment by harmoniqpunk** [comment]
Hi @larshesel. Thank you for support. In fact first time I have checked for `nil` and you have right, this is the main problem but later I have bypassed it to understand why does return `nil` because `$API_STAGE` looks like it is correctly set:

```
vernemq@broker-3325152631-yg68e:/$ echo $API_STAGE
dev 
```

It also return `nil` for `$VERNEMQ_VERSION`. 

Maybe I should opened issue on Luerl. However I will let it open also here and come back with the solution.

**LATER UPDATE:**

Looks like the erlang shell doesn't see the env variable:

```
root@broker-3325152631-yg68e:/# vernemq attach
Remote Shell: Use "Ctrl-C a" to quit. q() or init:stop() will terminate the vernemq node.
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.4  (abort with ^G)
(VerneMQ@10.2.69.6)1> os:getenv("API_STAGE") .
false
(VerneMQ@10.2.69.6)2> os:getenv("VERNEMQ_VERSION") .
false
```

```
(VerneMQ@10.2.69.6)1> os:getenv() .
["ERL_MAX_PORTS=65536","ERL_FULLSWEEP_AFTER=0",
 "ERL_CRASH_DUMP=/erl_crash.dump",
 "ERL_MAX_ETS_TABLES=256000","PWD=/usr/lib/vernemq",
 "SHELL=/bin/bash","ROOTDIR=/usr/lib/vernemq",
 "HEART_COMMAND=/usr/sbin/vernemq start",
 "PATH=/usr/lib/vernemq/erts-6.4/bin:/usr/lib/vernemq/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games",
 "TERM=xterm","_=/usr/sbin/vernemq","LOGNAME=vernemq",
 "BINDIR=/usr/lib/vernemq/erts-6.4/bin","PROGNAME=vernemq",
 "EMU=beam","OLDPWD=/usr/lib/vernemq",
 "HOME=/var/lib/vernemq","SHLVL=1","USER=vernemq",
 "MAIL=/var/mail/vernemq"]
```

```
root@broker-3325152631-yg68e:/# su vernemq
vernemq@broker-3325152631-yg68e:/$ printenv
HOSTNAME=broker-3325152631-yg68e
BROKER_PORT_443_TCP=tcp://10.3.0.196:443
SHELL=/bin/bash
KUBERNETES_PORT=tcp://10.3.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
TERM=xterm
BROKER_PORT=tcp://10.3.0.196:8883
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.3.0.1
BROKER_SERVICE_PORT_SSL=443
BROKER_SERVICE_PORT_MQTT=8883
USER=vernemq
BROKER_PORT_8883_TCP_ADDR=10.3.0.196
API_STAGE=dev
BROKER_SERVICE_HOST=10.3.0.196
MAIL=/var/mail/vernemq
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD=/
BROKER_PORT_443_TCP_PROTO=tcp
BROKER_SERVICE_PORT=8883
BROKER_PORT_8883_TCP=tcp://10.3.0.196:8883
BROKER_PORT_8883_TCP_PORT=8883
HOME=/var/lib/vernemq
SHLVL=2
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBE_VERNEMQ_DISCOVERY_URL=http://kubernetes-pod-ip-finder.default.svc.cluster.local/?app=broker&environment=dev
BROKER_PORT_443_TCP_ADDR=10.3.0.196
LOGNAME=vernemq
BROKER_PORT_8883_TCP_PROTO=tcp
VERNEMQ_VERSION=0.12.5p5
BROKER_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.3.0.1
KUBERNETES_PORT_443_TCP=tcp://10.3.0.1:443
_=/usr/bin/printenv
```

**Comment by larshesel** [comment]
Yes, as you found out VerneMQ doesn't inherit the current env when doing `vernemq start`, maybe you can work around that like in this: https://github.com/erlio/vmq_diversity/issues/4#issuecomment-222632656.

**Comment by harmoniqpunk** [comment]
Oh. Right above my nose and I didn't saw. Thank you.
