### ISSUE TITLE
does vmq_diversity support memcache?

### ISSUE THREAD

**Issue by andyfires** [erlio/vmq_diversity#8]
We want use lua script to communicate with memcache, does vmq_diversity support importing additional libary for memcache? Thanks.

**Comment by dergraf** [comment]
This would require to implement a memcache adapter in vmq_diversity similar to the one for redis. An Erlang client library for memcache exists https://github.com/EchoTeam/mcd so this seems fairly simple to do. @larshesel ?  ;)

**Comment by larshesel** [comment]
Hi - I've started adding memcached compatibility support into vmq_diversity - I'll see if I can push something later today or tomorrow. Looking at the available erlang drivers for memcached, theres `mcd` as @dergraf mentioned and I've based my work on that one for now - I may have to replace/improve it later as it doesn't seem to support things like `prepend`, `cas` and other operations. Just the 'normal set of operations like `add`, `set`, `get` `replace` etc (with flags and expirations). Would that be enough for your use-case @andyfires ?

**Comment by andyfires** [comment]
@larshesel Thank you very much for quick response. I am doing my work based on redis right now, but it will be great if you can add support for memcache so I can change my code on memcache later. I think you can just go ahead, I'll try if add, set, get, replace can fulfil my requirements first.

**Comment by larshesel** [comment]
Hi @andyfires we've added basic memcached functionality in PR #10. We'll likely be merging this later today.

**Comment by larshesel** [comment]
And it was just merged to master a moment ago, I hope you'll find it usable. And thank you for using VerneMQ! :)

**Comment by andyfires** [comment]
@larshesel Thank you!
