### ISSUE TITLE
Failing loading vmq_diversity plugin.

### ISSUE THREAD

**Issue by kendemu** [erlio/vmq_diversity#9]
I'm using Erlang OTP 18 and vernemq source master lastest commit.
I succeed in building vmq_diversity and also testing via `rebar3 ct` command, but I couldn't load the plugin in vernemq. I use rebar3 for building.

`vmq_admin plugin enable -n vmq_diversity -p /home/kendemu/vmq_diversity/_build/default`
`vmq_admin plugin enable -n vmq_diversity -p /home/kendemu/vmq_diversity/_build/default/lib/vmq_diversity`

then the following error happens : 
Invalid value: "/home/kendemu/vmq_diversity/_build/default" for flag: path

How could I solve this error?

**Comment by larshesel** [comment]
It looks strange that you 're enabling the plugin twice. Is that a cut and paste error? You should use the first form `vmq_admin plugin enable -n vmq_diversity -p /home/kendemu/vmq_diversity/_build/default`.

The error means that 1) either the plugin wasn't compiled or 2) VerneMQ does not have read access to the files or 3) the path is wrong.

**Comment by larshesel** [comment]
Closing this for now - please let us know if you're still having issues.

**Comment by rolandvar** [comment]
@larshesel i have the same error on Ubuntu 14.04.5 LTS with Erlang OTP 19.2
As you can see the path to the folder is correct but the plugin is unable to activate also while compiling I get errors is normal?

What am I doing wrong?

Thanks!

![github](https://cloud.githubusercontent.com/assets/2823810/21728422/6d4e31d8-d446-11e6-927f-cb7312b22831.png)

**Comment by larshesel** [comment]
Hi @Makingweb 

My best bet is that it's a file system permission issue. Which user is running VerneMQ? If it's not running as the root user then VerneMQ is not allowed to access the files you're pointing to.

Can you run a `ps -ef | grep beam` to see which user owns the VerneMQ beam process?

**Comment by larshesel** [comment]
Btw - I don't see any errors in your compilation output, just some warnings?

**Comment by rolandvar** [comment]
@larshesel 

I'm sorry you're right are warnings...

Here the  `ps -ef | grep beam` output:

`root@MYDROP1:~# ps -ef | grep beam
vernemq   2408  2406  0 19:00 pts/2    00:00:06 /usr/lib/vernemq/erts-7.3/bin/beam.smp -P 256000 -A 64 -K true -W w -- -root /usr/lib/vernemq -progname vernemq -- -home /var/lib/vernemq -- -boot /usr/lib/vernemq/releases/0.15.2/vernemq -config /var/lib/vernemq/generated.configs/app.2017.01.06.19.00.45.config -setcookie vmq -name VerneMQ@127.0.0.1 -smp enable -vm_args /var/lib/vernemq/generated.configs/vm.2017.01.06.19.00.45.args -pa /usr/lib/vernemq/lib/erlio-patches -- console
root      3904  1898  0 20:00 pts/0    00:00:00 grep --color=auto beam`

**Comment by larshesel** [comment]
Ok, so VerneMQ is running under as the `vernemq` user, so it doesn't have access to read the plugin files as they are in the root user directory.

It looks from the paths that you've installed VerneMQ from a package. Notice that VerneMQ packages are built with Erlang 18 and you should therefore also use Erlang 18.X to build plugins. Plugins built with erlang 19 will likely not function when run on an earlier erlang virtual machine.
